extends:
  - "./.eslintrc.yml"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
rules:
  "@typescript-eslint/indent":
    - 2
    - 2
    - SwitchCase: 1
      ignoreComments: false
  "@typescript-eslint/member-delimiter-style": 2
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/no-use-before-define":
    - 2
    - classes: false
  "@typescript-eslint/semi":
    - 2
    - always
  indent: 0
  keyword-spacing:
    - 2
    - after: true
  object-curly-spacing:
    - 2
    - always
  semi: 0
  sort-class-members/sort-class-members:
    - 2
    - order:
      - "[alphabetical-static-properties]"
      - "[properties]"
      - constructor
      - "[alphabetical-static-methods]"
      - "[alphabetical-methods]"
      - 'on'
      - "[everything-else]"
      - toString
      - toJSON
      groups:
        alphabetical-static-properties:
        - type: property
          static: true
          sort: alphabetical
          name: /^(?:(?:[A-Z]+)?[a-z0-9])(?:[a-zA-Z0-9]?)+$/
        alphabetical-static-methods:
        - type: method
          static: true
          sort: alphabetical
        events:
        - type: property
          name: /on/
